In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r'C:\Users\LENOVO LOQ\OneDrive\Desktop\Data science\work\customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
# here the previous purchase details are not available 
# we need to work with what we have

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [5]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [6]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [7]:
# need to correct null
# here the review column have null so taking median is not practical it will creaate bias
# so we will take median or each product based and will give that value
# so we need to group it by catagory and take the medians

In [8]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [9]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [10]:
# keeping column name in different formats will be difficult while coding
# so change all of them to floor case
# everything will be lower case and space will be underscore

In [11]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [12]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [13]:
# create a new column to age group
labels=['Young Adult','Adult','Middle-aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)
# qcut is used to divide the data into equal quantiles. 
# Here we are dividing the age column into 4 quantiles and labeling them as Young Adult, Adult, Middle-aged, and Senior.

In [14]:
# pd.qcut(): This function divides a numeric column into quantile-based bins.
# q=4 means you want to split the age column into 4 equal-sized groups (quartiles).
# Each group will contain roughly the same number of rows, not necessarily the same age range.

# labels=labels: Instead of default numeric bin labels (0,1,2,3), you assign custom names:
# First quartile → "Young Adult"
# Second quartile → "Adult"
# Third quartile → "Middle-aged"
# Fourth quartile → "Senior"
# Result: A new column age_group is added to your DataFrame. 
# Each person’s age is categorized into one of the four groups based on which quartile their age falls into.

In [15]:
# qcut: Splits data into quantiles (equal number of rows per bin).
# cut: Splits data into fixed value ranges that you define.
# Use qcut when you want balanced group sizes, and cut when you want meaningful ranges (like age brackets).
# example:-
# labels = ['Young Adult','Adult','Middle-aged','Senior']
# bins = [18, 30, 45, 60, float('inf')]   # fixed ranges
# df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=True)

# bins: Defines the cut points for age.
# [18, 30, 45, 60, inf] means:
# 18 ≤ age ≤ 30 → Young Adult
# 31 ≤ age ≤ 45 → Adult
# 46 ≤ age ≤ 60 → Middle-aged
# 61+ → Senior
# labels: Assigns human-readable names to each bin.
# right=True: Interval includes the right endpoint (e.g., 30 goes into Young Adult).
# You can set right=False if you want the left endpoint included instead.

In [16]:
df[['age','age_group']].head(10)
# really usefull for marketing and understanding the customer beahvior based on age group.

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [17]:
df['frequency_of_purchases'].unique()

<StringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str

In [18]:
# create a column purchase frequency days.
# frequency is in text so it is best and easier to handle non text data 
# converting human-readable purchase frequency labels into standardized numeric values (days) for easier analysis and computation.
# created a Python dictionary that maps textual purchase frequency labels to the equivalent number of days.
# Example: "Weekly": 7, "Monthly": 30.
freq_mapping={'Fortnightly':14,
              'Weekly':7,
              'Monthly':30,
              'Quarterly':90,
              'Bi-Weekly':14,
              'Annually':365,
              'Every 3 Months':90}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(freq_mapping)

In [19]:
df[['frequency_of_purchases','purchase_frequency_days']].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [20]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [21]:
(df['discount_applied']==df['promo_code_used']).all()
# it is to check both columns are same or not

np.True_

In [22]:
# since we have same two column values its not necessary
# so we drop one column
df=df.drop('promo_code_used',axis=1)
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [23]:
import sys
import subprocess
subprocess.check_call([sys.executable, "-m", "pip", "install", "pymysql"])

0

In [24]:
import pymysql
print("PyMySQL is installed successfully!")

PyMySQL is installed successfully!

In [25]:
# Format: mysql+mysqlconnector://<user>:<password>@<host>/<database>
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:root123@127.0.0.1:3306/customer_behavior"
)

with engine.connect() as connection:
    print("MySQL connected successfully!")

MySQL connected successfully!

In [26]:
df.to_sql(name="customer", con=engine, if_exists="replace", index=False)

3900

In [27]:
tables = pd.read_sql("SHOW TABLES", engine)
print(tables)

  Tables_in_customer_behavior
0                    customer